name: Reusable JsonRPC Test

on:
  workflow_call:
    inputs:
      test_node_addr:
        required: true
        type: string
      test_script:
        required: true
        type: string
      key_privateKey:
        required: true
        type: string

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Aspect Test
      run: |
        mkdir -p ci_scripts
        cat > ci_scripts/init_env.sh <<EOF
          source ~/.nvm/nvm.sh
          set -ex
          cd /test-scripts/pre_public_testnet/json-rpc
          sed -i "s|\"node\": \".*\"|\"node\": \"${{ inputs.test_node_addr }}\"|g" project.config.json && cat project.config.json
          echo '${{ inputs.key_privateKey }}' > privateKey.txt
          
          node ${{ inputs.test_script }}

        EOF
        chmod +x ci_scripts/init_env.sh
        docker run --name testenv -v $(pwd)/ci_scripts:/ci_scripts -i simonalphafang/artela-jsonrpc-testenv:0.0.1 /bin/bash -c /ci_scripts/init_env.sh